name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 16
      uses: actions/setup-java@master
      with:
        distribution: temurin
        java-version: 16
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload built JAR
      uses: actions/upload-artifact@master
      with:
        name: WiiLink-Bot.jar
        path: WiiLink-Bot.jar
