name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 16
      uses: actions/setup-java@master
      with:
        java-version: 16
    - name: Build with Maven
      run: mvn package --file pom.xml
    - run: mkdir out
    - run: mv target/WiiLink-Bot.jar out/
    - uses: actions/upload-artifact@master
      with:
        name: WiiLink-Bot
        path: out
